Feat: added periodic saves of config.json
Disservin/fast-chess pull request #355
Opened 2024-05-06 16:53 UTC by TheRealGioviok

So that no one must suffer anymore.

2024-05-06 20:16 UTC, gahtan-syarif commented
and for this one:
```
long unsigned int save_iter = 0;
```
i think that should be:
```
long unsigned int save_iter = initial_matchcount_;
```

2024-05-06 20:19 UTC, Disservin commented
please use the fixed size integer variants, std::uint32_t etc.

2024-05-06 20:59 UTC, TheRealGioviok commented
On it.

2024-05-06 21:40 UTC, TheRealGioviok commented
Should be working fine now. Tested it and it works. I also tried to follow the existing conventions for structs and so on.

2024-05-06 21:45 UTC, TheRealGioviok commented
All this well written repo is getting to me 😵 . Do I just run make update-man and commit the stuff?

2024-05-06 21:45 UTC, gahtan-syarif commented
and also for this:
```
Enables automatic save of the sprt state in the config.json file each N games played.
```
i suggest changing to
```
Enables automatic save of the tournament state in the config.json file each N games played.
```

2024-05-06 21:46 UTC, gahtan-syarif commented
> All this well written repo is getting to me 😵 . Do I just run make update-man and commit the stuff?

yeah, run make update-man locally in your computer and it would change the man.hpp file, then you replace the old man.hpp with the new one in your repo

2024-05-06 21:47 UTC, gahtan-syarif commented
> > All this well written repo is getting to me 😵 . Do I just run make update-man and commit the stuff?
> 
> yeah, run make update-man locally in your computer and it would change the man.hpp file, then you replace the old man.hpp with the new one in your repo

this is so that the new version would output the new man file when we run -help

2024-05-06 21:51 UTC, TheRealGioviok commented
![immagine](https://github.com/Disservin/fast-chess/assets/64363733/47138ef5-f9da-4b5e-b931-5f163e1ca15c)

Success! Any other things to fix?

2024-05-06 21:52 UTC, gahtan-syarif commented
> ![immagine](https://private-user-images.githubusercontent.com/64363733/328327945-47138ef5-f9da-4b5e-b931-5f163e1ca15c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMzI2MjUsIm5iZiI6MTcxNTAzMjMyNSwicGF0aCI6Ii82NDM2MzczMy8zMjgzMjc5NDUtNDcxMzhlZjUtZjlkYS00YjVlLWI5MzEtNWYxNjNlMWNhMTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDIxNTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNmQ4Y2JmY2Y5NWU3MWVlOWIzZDQ1OTM4YjY4M2IyNjAwY2M0MjdkMjhkZjc1ZWQwYWQ5Y2I5ODRmNGE3OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u3t35tSqP4a36WjeLHlwAwO3Q960rr_N9bxc3i-bJBA)
> 
> Success! Any other things to fix?

looks good to me, we'll wait for disservin

2024-05-07 21:28 UTC, Disservin requested changes

2024-05-07 21:28 UTC, Disservin commented on src/matchmaking/tournament/base/tournament.hpp
> +    ~BaseTournament() {
idk prefer if you kept `virtual` here

2024-05-08 06:07 UTC, merged