Scoreinterval
Disservin/fast-chess pull request #378
Opened 2024-05-11 01:10 UTC by gahtan-syarif

2024-05-11 06:59 UTC, Disservin requested changes

2024-05-11 06:59 UTC, Disservin commented on src/matchmaking/output/output_cutechess.hpp
> +        if (false) std::cout << first << second;
Remove the name from the parameter list

2024-05-11 06:59 UTC, Disservin commented on src/matchmaking/output/output_fastchess.hpp
> +        if (false) std::cout << first << second << stats.wins;
Same

2024-05-11 07:05 UTC, gahtan-syarif commented on src/matchmaking/output/output_cutechess.hpp
> +        if (false) std::cout << first << second;
wouldnt it just error?

2024-05-12 10:22 UTC, Disservin commented on src/matchmaking/output/output_cutechess.hpp
> +        if (false) std::cout << first << second;
```
(const Stats&, const std::string&, const std::string&)
```

2024-05-12 10:29 UTC, gahtan-syarif commented on src/matchmaking/output/output_cutechess.hpp
> +        if (false) std::cout << first << second;
updated

2024-05-12 10:32 UTC, gahtan-syarif commented on src/matchmaking/output/output_fastchess.hpp
> +        if (false) std::cout << first << second << stats.wins;
updated

2024-05-13 09:39 UTC, merged